### ISSUE TITLE
Amministratore: conferma e attiva nuovo beneficiario

### ISSUE THREAD

**Issue by mbonannotorp** [iltorpedone/socialmarket#12]
Sarebbe utile che conferma e attivazione di un nuovo beneficiario da parte dell'amministratore avvenissero con un solo passaggio. Quindi propongo un tasto/link "Conferma e attiva"

**Comment by olistik** [comment]
@mbonannotorp Era un bug. Al click del link di conferma veniva effettuata un'altra azione al posto della conferma. Per questo motivo risultava necessario attivare in seguito l'utente.
Ho corretto il link e aggiornato anche la dicitura suggerita in modo da comunicare più adeguatamente l'effetto dell'azione.
