### ISSUE TITLE
Spese da aggiungere

### ISSUE THREAD

**Issue by mbonannotorp** [iltorpedone/socialmarket#15]
Variare la dicitura "spese da aggiungere" in "variazione max spese".

## Richiesta originale

> Il valore che si inserisce nel campo "spese da aggiungere" nella scheda del beneficiario è un valore incrementale, non a sostituzione. Per intenderci, se un utente ha 20 spese, e gliene si vuole aggiungere 10, nel campo "spese da aggiungere" devo scrivere 10, e non 30. Il valore si deve sommare al precedente, non sostituire. Attualmente si sostituisce

**Comment by olistik** [comment]
@mbonannotorp attento che in questo modo diventa scomodo abbassare il numero massimo di spese (magari in seguito ad un errore) perché dovresti proporre un valore negativo per abbassare il numero max di spese.

Vuoi che si possano inserire valori negativi? O pensi ci sia qualche altro metodo comodo?

**Comment by mbonannotorp** [comment]
@olistik non è mai capitato di diminuire spese, ma hai ragione, potrebbe capitare, banalmente per errore. Allora potremmo variare la dicitura "spese da aggiungere" in "variazione max spese" così è chiaro che si deve inserire lì una variazione

**Comment by olistik** [comment]
@mbonannotorp Questa è ok?
