### ISSUE TITLE
Modifiche possibili per utente Negozio

### ISSUE THREAD

**Issue by mbonannotorp** [iltorpedone/socialmarket#17]
L'utente Negozio non può eliminare i beneficiari (togliere link Elimina)
Non può modificare le spese (solo l'amministratore può farlo) ma vederle in sola lettura una volta chiuse
Non può nè attivare nè modificare gli enti invianti (può vederli in sola lettura)
Le uniche modifiche che può fare nella scheda del singolo beneficiario è telefono, sesso e indirizzo. Le altre modifiche possono essere fatte solo dall'amministratore

**Comment by olistik** [comment]
@mbonannotorp 

Mi sono reso conto dopo che:

> Non può modificare le spese (solo l'amministratore può farlo) ma vederle in sola lettura una volta chiuse

Non va bene perché un negozio crea una spesa e la deve poter portare dallo stato _carrello_ allo stato _semi-chiuso_ fino allo stato _chiuso_.

Deve quindi poter vedere le spese che sono state iniziate ma che per qualche motivo (scheda del browser chiusa e poi riaperta) non sono ancora state né semi-chiuse, né chiuse.

Mi confermi che il negozio può quindi vedere tutte le spese?

Considera che **nessuno** può modificare una spesa chiusa definitivamente.

**Comment by olistik** [comment]
@mbonannotorp Mi sono portato avanti e ho ripristinato i permessi di visualizzazione e modifica sopra menzionati, per l'utente negozio.
Se mi dai conferma, chiudo la issue.

**Comment by olistik** [comment]
Anzi, la chiudo e se non va bene la riapriamo.
