### ISSUE TITLE
Aggiungere il logo

### ISSUE THREAD

**Issue by olistik** [iltorpedone/socialmarket#37]
![smk-logo 160307](https://user-images.githubusercontent.com/21038/50488560-652ae380-0a03-11e9-8993-bccf63492d74.png)

**Comment by olistik** [comment]
@mbonannotorp Dove vogliamo inserire il logo? Semplicemente centrato nella testata di ogni pagina?

**Comment by olistik** [comment]
@mbonannotorp Ho capito solo ora che il logo serve per la #26 , quindi chiudo questa issue e allego di la il logo. :-)

**Comment by mbonannotorp** [comment]
@olistik magari meglio in alto a sinistra piccolo così non ruba spazio, che dici?
