### ISSUE TITLE
Impostare il redirect da www.socialmarketnordmi.it all'indirizzo di Heroku

### ISSUE THREAD

**Issue by olistik** [iltorpedone/socialmarket#38]
- [x] sito con index.html che effettua una redirezione con window.location (repository qui su GitHub)
- [x] collegamento con Netlify
- [x] impostazione DNS sul sito Netlify (in carico a @mbonannotorp una volta svolti i punti precedenti)

**Comment by olistik** [comment]
@mbonannotorp Basta modificare il CNAME `www` in `socialmarket.netlify.com` (senza `http://`).

**Comment by olistik** [comment]
@mbonannotorp Puoi impostare questi nameserver?

- dns1.p01.nsone.net
- dns2.p01.nsone.net
- dns3.p01.nsone.net
- dns4.p01.nsone.net

**Comment by mbonannotorp** [comment]
@olistik attualmente come nameserver e come mail server utilizziamo quelli di aruba (che è la schermata che ho allegato, te la riallego completa
![image](https://user-images.githubusercontent.com/45065200/51027026-2b73e400-1590-11e9-90b6-9e526b163654.png)
Mi confermi che quindi lascio invariati i mail server (con cui usiamo la mail) e modifico invece la prima parte indicando altri nameserver?

**Comment by olistik** [comment]
@mbonannotorp confermo. 👍

**Comment by olistik** [comment]
@mbonannotorp Prova a verificare il comportamento del sito e dimmi se funziona.

**Comment by mbonannotorp** [comment]
Viene reindirizzato correttamente. Chiudo issue e cambio password?

**Comment by olistik** [comment]
@mbonannotorp Bene. Sì, cambia la password che non ho più bisogno di accedere al pannello.

**Comment by olistik** [comment]
@mbonannotorp La issue è già stata chiusa nel momento in cui l'ho completata.
Avresti potuto riaprirla nel caso in cui non fosse stata risolta. In questo caso invece (corretta implementazione) puoi spostarla nella colonna "Accepted" nella pagina del progetto: https://github.com/iltorpedone/socialmarket/projects/1
