### ISSUE TITLE
Utente non si cancella

### ISSUE THREAD

**Issue by mbonannotorp** [iltorpedone/socialmarket#41]
Quando l'amministratore cancella un utente (in particolare utente Matteo Marse) il sistema dice che l'utente è stato cancellato con successo, ma permane nell'elenco

**Comment by olistik** [comment]
@mbonannotorp Potrebbe non essere un problema.

```ruby
pp User.where(full_name: 'Marse').as_json

[{"id"=>11,
  "full_name"=>"Marse",
  "email"=>"__deleted__matteo@marse.it",
  "created_at"=>Tue, 13 Nov 2018 16:25:18 UTC +00:00,
  "updated_at"=>Fri, 21 Dec 2018 08:32:34 UTC +00:00,
  "app_role"=>"provider",
  "is_active"=>true,
  "deleted"=>true},
 {"id"=>12,
  "full_name"=>"Marse",
  "email"=>"amministrazione@marse.it",
  "created_at"=>Thu, 15 Nov 2018 09:56:37 UTC +00:00,
  "updated_at"=>Mon, 07 Jan 2019 16:16:30 UTC +00:00,
  "app_role"=>"provider",
  "is_active"=>true,
  "deleted"=>false}]
```

Nel sistema sono presenti due utenti con il nome `Marse`.
Quello cancellato aveva l'e-mail `matteo@` mentre quello rimasto ha l'e-mail `amministrazione@`.
Penso quindi che la cancellazione sia avvenuta con successo.

Ti torna?

**Comment by mbonannotorp** [comment]
Un utente si chiamava "Matteo Marse" e aveva come mail matteo@marse.it. L'altro si chiama "Marse" e ha come mail amministrazione@marse.it. Io ho cancellato "Matteo Marse" ma è ancora nell'elenco, come puoi vedere dallo screenshot allegato
![image](https://user-images.githubusercontent.com/45065200/50952229-0a3bc680-14b0-11e9-9db7-b1ac62f3e5f8.png)

**Comment by olistik** [comment]
@mbonannotorp Ho capito il motivo. Un utente con la stessa e-mail era già stato cancellato e la strategia di cancellazione "soft" andava a collidere. L'ho fixato.
