### ISSUE TITLE
Autorizzazioni utenti

### ISSUE THREAD

**Issue by olistik** [iltorpedone/socialmarket#6]
## Negozio

Il negozio può vedere e modificare le informazioni dei beneficiari (ma non cancellarli né inserirli), non vede città, non vede categorie, vede enti invianti ma solo in lettura, può gestire tutto sulle spese, non vede gli utenti, non vede il magazzino

## Magazzino

Il magazzino può fare tutto quello che fa il negozio + gestire il magazzino.

**Comment by olistik** [comment]
Già risolto dalle altre issue.

**Comment by mbonannotorp** [comment]
Togliere il tasto "Nuovo beneficiario". L'utente negozio non può inserire nuovi beneficiari
